# Setup
title: Strange Pixels
tagline: 
url: http://127.0.0.1:4000
paginate: 6
baseurl: ""
permalink: pretty


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Neal Gillis
  url: 
  email: 

# Custom vars
version: 3.0.0

# Used instead of site title in masthead
headerimg: assets/images/strange_pixels.png

# Links in the top right main navigation
mainnav:
  - title: About
    url: /about
  - title: Archive
    url: /archive


